# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium import webdriver

class TestSmokeTest():
    def setup_method(self, method):
        options = Options()
        options.add_argument("--headless=new")
        self.driver = webdriver.Chrome(options=options)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_logoHeaderandTitle(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
        self.driver.set_window_size(705, 816)
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
        assert len(elements) > 0
        assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
        assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
        assert self.driver.title == "Teton Idaho CoC"

    def test_adminPageUsernamePassword(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
        self.driver.set_window_size(705, 816)
        self.driver.find_element(By.CSS_SELECTOR, "#hamburger-equiv > img").click()
        self.driver.find_element(By.LINK_TEXT, "Admin").click()
        elements = self.driver.find_elements(By.ID, "username")
        assert len(elements) > 0
        self.driver.find_element(By.ID, "username").send_keys("Gabriela")
        self.driver.find_element(By.ID, "password").send_keys("wrongpass")
        self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()

        # Wait for error message to appear
        time.sleep(0.5)
        assert self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").text == "Invalid username and password."

    def test_directoryGridandListfeature(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
        self.driver.set_window_size(774, 816)
        self.driver.find_element(By.CSS_SELECTOR, "#hamburger-equiv > img").click()
        self.driver.find_element(By.LINK_TEXT, "Directory").click()
        self.driver.find_element(By.ID, "directory-grid").click()
        assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
        self.driver.find_element(By.ID, "directory-list").click()
        assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"

    def test_joinPageDataEntry(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
        self.driver.set_window_size(779, 816)
        self.driver.find_element(By.LINK_TEXT, "Join Us").click()
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".myinput:nth-child(2)")
        assert len(elements) > 0

        self.driver.find_element(By.NAME, "fname").send_keys("Gabriela")
        self.driver.find_element(By.NAME, "lname").send_keys("Rivera")
        self.driver.find_element(By.NAME, "bizname").send_keys("Cse")
        self.driver.find_element(By.NAME, "biztitle").send_keys("Software Dev")
        self.driver.find_element(By.NAME, "submit").click()

        elements = self.driver.find_elements(By.NAME, "email")
        assert len(elements) > 0

    def test_navigatetothehomepage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
        self.driver.set_window_size(782, 816)
        assert len(self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1 > .centered-image")) > 0
        assert len(self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2")) > 0
        assert len(self.driver.find_elements(By.LINK_TEXT, "Join Us!")) > 0
        self.driver.find_element(By.LINK_TEXT, "Join Us!").click()
        assert self.driver.title == "Teton Idaho CoC"
